name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.21", "1.22"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v -coverprofile=profile.cov ./...
        cd pkg/ctlrhelper && go test -v ./...

    - name: Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
